### ISSUE TITLE
Sadly none of 2N2369A work in these pcb boards. There is no oscillation!

### ISSUE THREAD

**Issue by Alectronics** [podonoghue/Jim_Williams_Pulse_Generator#2]
There must be something very wrong with these OSH Park pcb boards of Jim Williams Fast Rise Pulse Generator. I've tested my brandnew 2N2369A in part of Kerry Wong's transistor circuit with the external 120V input with 220Kohm resistor in the collector of my transistor under test. It worked splendidly at around 119V input giving about 40V on the avalanching collector of the transistor under test. And my Tektronix oscilloscope showed a frequency that depended on the recovery time of the transistor,  and also showed a fine Avalanche pulse when was 'zoomed' in on the pulse.
But the same new transistors (10 brandnew ones from Digikey!) never worked in the OSH Park boards I received! I used exactly the listed components from version March 2017 also v2.4, but only the LT1073 works giving about 89V DC on the collector serieresistance of the 2n2369A. 
So I am almost sure that these sold boards have some kind of HF failure or any other design flaw! Because the transistors when used in the OSH Park boards never work as intended and it was all a very expensive and useless project! And I hate to say this but someone is selling crap and boards that are just not working!

**Comment by podonoghue** [comment]
Hi Alectronics,
I'm sorry to hear of your problems.
I don't really have any insight into the results you are getting.
I only built 1 board using a PCB from OSH Park and it worked fine.
A further 10 were built for a lab class but used PCBs from JLCPCB - they also worked,
Leakage on the PCB could be a problem but I would really think it unlikely to be a issue.
I don't know if soldering residue (cooked flux) could be an issue.
The circuit relies on the breakdown of the transistor which is **not** well defined and it may be necessary to select transistors.  I bought from a couple of suppliers in case there was a variation in the breakdown threshold but found all I tried worked (11).
I'm not sure where the one from OSH park is now and I don't have access to the 10 at work so I can't check the voltages on them.  I'll hunt around and see if I can find the OSH park one for voltage measurement.
Good luck.

**Comment by Alectronics** [comment]
Thanks podonoghue for the fast reply. I also tried if the transistor would oscillate if I provided the collectorvoltage externally but it still failed to work. So the design is flawed since I can't find any issue on the board after rechecking, Also I tried to adjust the 1.8pF caps by doubling those as also the 10uF on the 5V input but without any success. Still I wonder if I should change Ilim from 100 ohm to a 220 ohm resistor like is given in all other LT1073 operated pulser circuits, including in the LT1073 datasheet.

**Comment by podonoghue** [comment]
Hi,
I'm sorry I didn't read you original posting very well.
I don't have the circuit to check voltages but it is not designed to produce such a high voltage - obviously since the caps (C2) are specified as 100V.  The 2N2369 would be expected to break down at less than this since its Vcbo is only 40V.  89V sound like a plausible value for the voltage and I would expect it to be adequate.
The AN72 App Note provided on the main page discusses the operation and suggests a generated voltage of only 90 volts which shows the LT1073 is functioning as expected.
The Ilim resistor is not critical but you are welcome to try changing it.

I think it is likely the transistors that you are using have a better breakdown voltage than expected.
It is not uncommon for manufacturers to 'improve' transistors - actually fold together lines by using later generation devices with better but compatible specs.
I would suggest trying transistors from a different supplier but there are no guarantees.

I have no explanation why it wouldn't work with an external supply.
There is not much to go wrong!
What voltage (unchanging) appears across the 50 ohm resistor? If it is zero it would indicate that the transistor is not breaking down or is there some leakage leading to a higher fixed value? 
What voltage appear at the collector? If it is the same as V++ which would indicate that the transistor is not breaking down or is there some leakage leading to a lower value? 

The base voltage should be pulsing.  If zero the device is not breaking down.

bye

**Comment by Alectronics** [comment]
Okay understood!
I was afraid that you where going to say something like that.
I bought my 2N2369A from digikey and a second order with other parts is underway. Also some BSX20 types. But since they do work perfectly in Kerry Wong's DIY Pulse Giver the design of your from OSH Park bought boards is flawed!
The CE voltage should be much higher to always work!
I know because if the starting voltage is much higher they function fine as intended! Tested with my DY294 as DC voltage provider and Kerry Wong's transistor circuit. But still not in these pcb boards even if we provide a higher voltage externally onto the 1Mohm resistor on the collector! 
And some kind of warning about this would have been appreciated! Because now I spend over 140 USdollar on making 2 boards that simply never work!
By the way : the transistor pulsates, but terribly wrong at random giving a completely useless large pulsating about ~2 Hz signal on which we even if we would try never can trigger our scope with! And only in Kerry Wong's circuit using the same transistor we get a nice oscillating LF (about 80 KHz or similar) frequency with the needed fast rise pulse in each period! So something is wrong with the OSH Park boards or the design of it! And why this circuit also completely fails when a higher voltage externally is supplied is still a mystery!
For now I gave up on these nicely manufactured but sadly useless boards. 
PS: Sadly also changing the iLim resistor from 100 ohm into a 220 ohm value like advised in the datasheets made no positive change either. As also doubling the 10uF and the 1.8pF caps made no difference. It would be most helpful if a transistor curve trace with additional specs was given of the transistors that do work in these OSH Park boards. Because that would save me from having to repeat having to desolder and resolder failing 2N2369(A) transistors and help me to immediately select the right transistor pre-soldering with my Peak Atlas DCA 75 that incorporates a curve tracer. And my DY294 is capable in determing the breakdown avalanche level without destroying any component!

Albert.
________________________________
Van: podonoghue ***@***.***>
Verzonden: zondag 23 mei 2021 12:43
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,
I'm sorry I didn't read you original posting very well.
I don't have the circuit to check voltages but it is not designed to produce such a high voltage - obviously since the caps (C2) are specified as 100V. The 2N2369 would be expected to break down at less than this since its Vcbo is only 40V.

I think it is likely the transistors that you are using have a better breakdown voltage than expected.
It is not uncommon for manufacturers to 'improve' transistors - actually fold together lines by using later generation devices with better but compatible specs.
I would suggest trying transistors from a different supplier but there are no guarantees.

bye

**Comment by podonoghue** [comment]
Hi,
I have linked to the two Application notes on the main Github page that describe this circuit and discuss transistor selection but I should draw more attention to the consideration of the transistors.  I have now done this.  Note that schematic states:

**May need to try several  2N2369s to obtain one that avalanches in a suitable fashion.Try to obtain from different batches (suppliers).**

As a data point all 11 boards that we built worked.  The transistors used were purchased on two occasions several years apart so I did not think it that critical of transistor devices.  For the prototypes I built, the devices were purchased from Element-14 in Australia (see part number in PDF) and are **2N2369** not **2N2369A**.  They are now marked as unavailable and obsolete on E-14. I cannot check the boards that were built where I formerly worked that were done more recently.  The transistor availability situation is similar on Digikey with 2N2369 as non-stocked.  It looks like they are generally unavailable.
The use of 2N2369A may account for the differing results.  Yes they have the same breakdown spec. but this is a minimum value and may have improved on the A version due to process changes.
I have not had anyone else report difficulties but I have no idea whether others have been built nor how recently.

The differing results for the actual boards is incomprehensible.  The PCB design is not particularly critical to work.  It simply minimises the capacitance at the emitter to ensure the fastest rise times.  Even if capacitance is excessive, or the layout changed, it should at least oscillate if you apply an external voltage sufficient to cause breakdown as you have done.  It is basically a relaxation oscillator - there is not much to go wrong!

If you like you can post photographs of the bare (if available) and assembled boards to see if I can spot anything amiss with the boards.  I assume the components used have appropriate voltage ratings but I doubt this would be an issue as 0805 size was used on the board (typically ~150V rating for resistors).

bye

**Comment by Alectronics** [comment]
Thank you very much podonoghue for that clear explanation!

That must be the reason since both my boards are indeed made with 2N2369A types that apparently completely fail to oscillate in the fast kHz range!
And these were apparently produced in India at that time according to the Digikey sheet. That also mentioned that they were PBfree.
Good that you added this fact to the design publication.
Maybe they left out the gold substance in the manufacturing process of the transistor in the newer types? Like the gold they used in those Russian tunneldiodes that also qualify to work in use as fast avalanche pulser?

I do hope that these Jim Williams boards will still become useful when the right transistor somewhere becomes available? Maybe my ordered BSX20 will work?
Anyway thanks for your fast and clear reply!
All the Best!

________________________________
Van: podonoghue ***@***.***>
Verzonden: maandag 24 mei 2021 05:26
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,
I have linked to the two Application notes on the main Github page that describe this circuit and discuss transistor selection but I should draw more attention to the consideration of the transistors. I have now done this.

As a data point all 11 boards that we built worked. The transistors used were purchased on two occasions several years apart so I did not think it that critical of transistor devices. For the prototypes I built, the devices were purchased from Element-14 in Australia and are 2N2369 not 2N2369A. They are now marked as unavailable and obsolete on E-14. I cannot check the boards that where built were I formerly worked that were done more recently. The transistor availability situation is similar on Digikey with 2N2369 as non-stocked. It looks like they are generally unavailable.
The use of 2N2369A may account for the differing results. Yes they have the same breakdown spec. but this is a minimum value and may have improved on the A version due to process changes.
I have not had anyone else report difficulties but I have no idea whether others have been built nor how recently.

The differing results for the actual boards is incomprehensible. The PCB design is not particularly critical to work. It simply minimises the capacitance at the emitter to ensure the fastest rise times. Even if capacitance is excessive, or the layout changed, it should at least oscillate if you apply an external voltage sufficient to cause breakdown as you have done.

bye

**Comment by Alectronics** [comment]
Update: This morning I also tested one 2N2369 without the A that was supposed to work in these OSH Park boards. Sadly it didn't! Again there was no avalanche oscillation only a low LF rimpel. But before I placed it over into the OSH Park pcb it worked splendidly in Kerry Wong's design producing an about 70 kHz avalanche oscillation! And a nice triggerable fast rise pulse too!
I am afraid that this again proves that the OSH Park design no longer works and not should be build without the exact right but no longer available transistor! And it really looks like that the board design or its no longer working circuit has something to do with the never working Jim Williams avalanche effect on these OSH Park boards.

________________________________
Van: Albert van bemmelen ***@***.***>
Verzonden: maandag 24 mei 2021 08:34
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)

Thank you very much podonoghue for that clear explanation!

That must be the reason since both my boards are indeed made with 2N2369A types that apparently completely fail to oscillate in the fast kHz range!
And these were apparently produced in India at that time according to the Digikey sheet. That also mentioned that they were PBfree.
Good that you added this fact to the design publication.
Maybe they left out the gold substance in the manufacturing process of the transistor in the newer types? Like the gold they used in those Russian tunneldiodes that also qualify to work in use as fast avalanche pulser?

I do hope that these Jim Williams boards will still become useful when the right transistor somewhere becomes available? Maybe my ordered BSX20 will work?
Anyway thanks for your fast and clear reply!
All the Best!

________________________________
Van: podonoghue ***@***.***>
Verzonden: maandag 24 mei 2021 05:26
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,
I have linked to the two Application notes on the main Github page that describe this circuit and discuss transistor selection but I should draw more attention to the consideration of the transistors. I have now done this.

As a data point all 11 boards that we built worked. The transistors used were purchased on two occasions several years apart so I did not think it that critical of transistor devices. For the prototypes I built, the devices were purchased from Element-14 in Australia and are 2N2369 not 2N2369A. They are now marked as unavailable and obsolete on E-14. I cannot check the boards that where built were I formerly worked that were done more recently. The transistor availability situation is similar on Digikey with 2N2369 as non-stocked. It looks like they are generally unavailable.
The use of 2N2369A may account for the differing results. Yes they have the same breakdown spec. but this is a minimum value and may have improved on the A version due to process changes.
I have not had anyone else report difficulties but I have no idea whether others have been built nor how recently.

The differing results for the actual boards is incomprehensible. The PCB design is not particularly critical to work. It simply minimises the capacitance at the emitter to ensure the fastest rise times. Even if capacitance is excessive, or the layout changed, it should at least oscillate if you apply an external voltage sufficient to cause breakdown as you have done.

bye

**Comment by podonoghue** [comment]
Hi,

Well I'm stumped if it didn't work with a genuine  2N2369.  There is not much to go wrong.
 
I'm sorry you have spent so much time and expense on this without success.

bye

**Comment by Alectronics** [comment]
Yes indeed, it was a bad experience after all the work done without any success. I hope it will save others the time and trouble also without them finding the right as original planned 2N2369 that would make this pcb design work.
By-the-way: I also tried if the 90V DC voltage coming out of the LT1073 on the OSH Park board would work on the testcircuit I used from Kerry Wong's design to test my 2N2369A and 2N3904 transistors with. That worked splendidly! So the voltage generator on the OSH Park is fine, Just the transistor on the OSH Park board somehow fails to oscillate in a useful manner. Several were tested invain including the 2N3904,

Best regards!

________________________________
Van: podonoghue ***@***.***>
Verzonden: maandag 24 mei 2021 15:38
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,

Well I'm stumped if it didn't work with a genuine 2N2369. There is not much to go wrong.

I'm sorry you have spent so much time and expense on this without success.

bye

**Comment by Alectronics** [comment]
PS: We can boost the output of this circuit to about 130V DC by increasing the value of the 10Mohm resistor going from output voltage to LT1073 pin FB. According to the LT1073 formula: output voltage = 212mV x ((+10Mohm/24kohm)+1). And when 10Mohm becomes about 13,8Mohm it will output at least 121V DC. Which means you also must use higher voltage 0.47uF capacitors! I was able to generate 136.2V over output voltage at C2 and 73.8V over C1 with 69.9V over C3. This will activate the standard 2N2369A transistors used on this board. However the OSH Park pcb design is still bad because the Kerry Wong design produces better signals with a much higher frequency and better triggerable scope signals. With the same 2N2369A transistor being used!
Just by using Kerry Wong's very small transistor circuit build on a small cheap and simpel pcb worked splendidly and gave much better results with any transistor and the same DC operating voltage as when they were placed on the bad and terribly failing OSH Park boards! Instead of the 22pF capacitor that Kerry used I replaced it with a 5...27pF 100V capacitor (the same as used on the bad OSH Park boards) and with it we can increase the frequency and at the same time decrease the signal amplitude.

**Comment by Alectronics** [comment]
These first 3 photos show the perfect working Kerry Wong's pcb. The following 2 photos on the right are the bad results of the OSH Park board AFTER the voltage first was increased to about 136V DC instead of 89V. Both boards used the same 2N2369A transistor!

________________________________
Van: Albert van bemmelen ***@***.***>
Verzonden: maandag 24 mei 2021 15:47
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)

Yes indeed, it was a bad experience after all the work done without any success. I hope it will save others the time and trouble also without them finding the right as original planned 2N2369 that would make this pcb design work.
Best regards!

________________________________
Van: podonoghue ***@***.***>
Verzonden: maandag 24 mei 2021 15:38
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,

Well I'm stumped if it didn't work with a genuine 2N2369. There is not much to go wrong.

I'm sorry you have spent so much time and expense on this without success.

bye

**Comment by podonoghue** [comment]
Hi,
I don't see much use in trying to increase the voltage for my design as I have no idea why it doesn't work with higher voltage as you have tried.  You would also need to carefully choose the SMT components to satisfy the higher voltage requirements in particular the capacitors and resistors.

I can't see the images you refer to.  Are they attached?
I have had a (brief!) look at a web site for Kerry Wong that shows a simple pulser on breadboard.  Is this what you are referring to?
http://www.kerrywong.com/2013/05/18/avalanche-pulse-generator-build-using-2n3904.  I note the capacitor values used are much larger - I would be worried about the longevity of the transistor!

Note that to get meaningful rise-time measurements on an oscilloscope you need to use a longer pulse - the co-axial storage line is **really necessary**.

The results I posted here https://github.com/podonoghue/Jim_Williams_Pulse_Generator appear somewhat better than at the above site for what it's worth but they were measured with a 500MHz oscilloscope so it may be an unfair comparison.

PS.
R6+C7 do not replace C5/C6.  They were an attempt to extend the pulse width and alter its shape.  The directly connected delay line functions much better. 

bye

**Comment by Alectronics** [comment]
I tried to upload the photos to this website but that seems not possible?
So I first emailed to you and noticed the website only mentioned them without showing them.
And I agree with your worries about the higher voltage problem on the used resistors and capacitors. I already bought 1206 250V 470nF caps for the about 30V higher voltage upgrade.
The Kerry Wong weblink is the correct one.
About the voltage upgrade on these OSH Park boards, it needs at least about 122,5V before apparently ST 2N2367A or other manufacturer's type A's or the transistors without the A (the one I had tested) work in this design.
And of course I already have seen the github downloadlink but it strangely gave an older februari 2017 2.4 version, after which a new version 2.4 march 2017 with a changed trimmer cap value in it was shown?

About the 20V output pulse on Kerry's and some other circuits I also am aware of the danger when we might blow up the 50 ohm input resistor in our oscilloscopes if the input current exceeds the maximum limit.

Anyhow the higher voltage upgrade for this OSH Park circuit to avalanche also with the present newer 2N2369A types is I am afraid to say quite necessary because with only <90V DC nothing works as expected! And certainly not as was shown in the links when the originally used and good avalanching 2N2369 transistors were still available.




________________________________
Van: podonoghue ***@***.***>
Verzonden: donderdag 27 mei 2021 06:27
Aan: podonoghue/Jim_Williams_Pulse_Generator ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [podonoghue/Jim_Williams_Pulse_Generator] Sadly none of 2N2369A work in these pcb boards. There is no oscillation! (#2)


Hi,
I don't see much use in trying to increase the voltage for my design as I have no idea why it doesn't work with higher voltage as you have tried. You would also need to carefully choose the SMT components to satisfy the higher voltage requirements in particular the capacitors and resistors.

I can't see the images you refer to. Are they attached?
I have had a (brief!) look at a web site for Kerry Wong that shows a simple pulser on breadboard. Is this what you are referring to?
http://www.kerrywong.com/2013/05/18/avalanche-pulse-generator-build-using-2n3904. I note the capacitor values used are much larger - I would be worried about the longevity of the transistor!

Note that to get meaningful rise-time measurements on an oscilloscope you need to use a longer pulse - the co-axial storage line is really necessary.

The results I posted here https://github.com/podonoghue/Jim_Williams_Pulse_Generator appear somewhat better than at the above site for what it's work but they were measured with a 500MHz oscilloscope so it may be an unfair comparison.

bye

**Comment by podonoghue** [comment]
Hi,
You should be able to add images by drag and drop on Github.
I'll try below:
![Pulse_3D_Perspective](https://user-images.githubusercontent.com/1848579/119770597-bce51600-beff-11eb-8f0f-34252983bb47.png)

**Comment by Alectronics** [comment]
![Kerry comp side](https://user-images.githubusercontent.com/84627300/119771563-322ff700-bebe-11eb-8785-5f48052243c4.JPG)

![Kerry's nice oscillation!](https://user-images.githubusercontent.com/84627300/119771615-47a52100-bebe-11eb-9c56-232323cd0b73.JPG)
![Good Kerry's signal](https://user-images.githubusercontent.com/84627300/119887003-e324a900-bf33-11eb-8449-8ceb8c16c835.JPG)

Above photo's show the Kerry Wong board I made to test the present 2N2369A types with successfully. Next photos show the bad and strange OSH Park curves after I 'upgraded' the Uce voltage to about 136V DC.
![OSH Park signal](https://user-images.githubusercontent.com/84627300/119771857-9d79c900-bebe-11eb-87eb-75a461843058.JPG)
![OSH_Park signal1](https://user-images.githubusercontent.com/84627300/119771879-a7033100-bebe-11eb-8d1a-07a8f65dc861.JPG)

**Comment by Alectronics** [comment]
Above scopesignals of Kerry's and the Osh Park board were both made with the exact same DC voltage of well over 90V. (136V DC!). And Kerry's circuit also works below 90V DC but it at best needs at least about 122.5V DC on the 220 kohm input resistor to the collector of the 2N2369A. Because around 58V DC the scope avalanche pulse signal of Kerry's board already starts to dim! And below that supply voltage to the 220kohm input the scope pulse vanishes completely. And the OSH Park never gives a steady triggerable pulse if any! Not even at the measured 89V DC!

**Comment by Alectronics** [comment]
PS: Maybe the results are better when the high voltage 1206 0.47uF 250V capacitors and the 1206 3.9Mohm resistors that were also ordered are finally here to replace the present 100V caps and add a 3.9Mohm serial resistorvalue to the present 10Mohm resistor to FB of the LT1073. But I'm afraid that the OSH Park board still won't work as expected because even when an excellent ripple-free DC signal is externally fed to the collector via a 220 kohm resistor the signal is still strange and distorted. And when I feed the OSH Park board from its microUSB connection it gives the same but very weak signal that is very hard to trigger on and way too unsteady to show on the scopescreen. Next photo shows the externally fed OSH Park board and the resulted strange scopesignal.
![OSH Park external fed](https://user-images.githubusercontent.com/84627300/119843585-fb7ece80-bf07-11eb-865f-27893ffdda6b.JPG)
![Strange pulse OSH Park](https://user-images.githubusercontent.com/84627300/119843673-0df90800-bf08-11eb-828e-84de3776ce27.JPG)

And next photo shows the almost perfect signal of the previously shown Kerry Wong transistor board when fed by the same DC voltage. (with a little ringing in the falling edge).
![Almost correct Kerry Wong pulse](https://user-images.githubusercontent.com/84627300/119844343-a3949780-bf08-11eb-97f0-9fcd20fa2aba.JPG)
Notice here that Kerry Wong's above shown fast rise pulse practically represents the exact bandwidth of my Tektronix 2465A oscilloscope which is 350 MHz!
The signal output of Kerry Wong's transistor weakens by starting to dim on the scopescreen when the voltage dropped to about 58V DC but still kept its same shape. Below that voltage it vanishes completely. But the OSH Park board sadly was not triggerable even when fed by its own LT1073 generated 90V DC voltage. I am not sure if it are the China LT1073 chips that have something to do with this because one of the five received was already completely defect, and a second one only produced 50V max output. And chips 3 and 4 were fine each producing 89V DC. Chip 5 wasn't tested. Good to know in this respect is that the Kerry Wong testboard with 2N2369A transistor worked splendidly with 90V DC and less! And maybe it is also worth a try if the OSH Park board still fails when the output voltage is enhanced to about 130V DC to also try if doubling the 470nF (0.47uF) capacitors each to about 940nF (like the 1uF caps that Kerry used in his 120V generator) will help? Which is easy by soldering a second cap on top of the first one. Because I now still used my perfect DY294 tester with 400V buffer ecap to provide an excellent ripple-free high DC supply voltage to the Jim Williams boards because the LT1073 89V DC output voltage on the OSH Park board apparently is inadequate to provide for a good working output signal on the OSH Park transistor.

**Comment by Alectronics** [comment]
Update: only AFTER the collector resistor was reduced from 1Mohm to 220Kohm and the C2 0,47nF cap was replaced by a 250V max capacitor, (C1 and C3 are still below 63V DC so 100V max still okay!) plus 10Mohm R3 was increased to 13,9 Mohm (by adding a 3,9Mohm in serie) the voltage became high enough to make avalanche oscillate the present 2N2369A transistors working on the 125V generated voltage by chip LT1073!
